name=DS1302
version=1.0.0
author=Wouter Piso
maintainer=Wouter Piso
sentence=A C++ library to use DS1302 RTC chip.
paragraph=A C++ library to use DS1302 RTC chip.
category=Device Control
url=https://github.com/Wouterpiso/DS1302_RTC_library 
architectures=esp32-wroom, Arduino Uno