name=DS1302
version=0.0.1
author=Wouter Piso
maintainer=Wouter Piso
sentence=A C/C++ library to use DS1302 RTC chip.
paragraph=A C/C++ library to use DS1302 RTC chip.
category=Device Control
url=https://github.com/Wouterpiso/DS1302_RTC_library 
architectures=esp32-wroom